<script type="text/javascript">
<!-- 
document.writeln(" <html> "); 
document.writeln("  "); 
document.writeln(" <body bgcolor=\"#FFFFCC \"onload=\"javaScript:RefreshPage(3000);\"  > "); 
document.writeln("  "); 
document.writeln("     <div id=\"content\"> "); 
document.writeln("    	<div id=\"container\"> "); 
document.writeln("     	 "); 
document.writeln("        <div id=\"map\"> "); 
document.writeln("            "); 
document.writeln(" 		 "); 
document.writeln(" 		<?php "); 
document.writeln(" 	include(\"header.js\"); "); 
document.writeln(" 	include(\"top.js\"); "); 
document.writeln(" 	$companyId=intval($_GET['companyId']); "); 
document.writeln(" error_reporting( error_reporting() & ~E_NOTICE ); "); 
document.writeln(" 	  error_reporting( error_reporting() & 0 ); "); 
document.writeln("         "); 
document.writeln(" 	 "); 
document.writeln(" 	if(isset($_POST['update_send'])) "); 
document.writeln(" 		{ "); 
document.writeln(" 			$companyName=$_POST['update_companyName']; "); 
document.writeln(" 			$contactPerson_name=$_POST['update_contactPerson_name']; "); 
document.writeln(" 			$adress=$_POST['update_adress']; "); 
document.writeln(" 			$password=$_POST['update_password']; "); 
document.writeln(" 			 "); 
document.writeln(" 			 "); 
document.writeln(" 			 "); 
document.writeln("  "); 
document.writeln(" 			mysql_query(\"UPDATE company SET password='$password'	,contactPerson_name='$contactPerson_name',adress='$adress',companyName='$companyName'				 WHERE companyId='$companyId'\"); "); 
document.writeln(" 			 "); 
document.writeln(" 			mysql_query(\"UPDATE user SET userName='$userName' WHERE userId=(SELECT userId FROM company WHERE companyId='$companyId')\"); "); 
document.writeln(" 		} "); 
document.writeln(" 		 "); 
document.writeln(" 		 "); 
document.writeln(" 		$company=mysql_fetch_array(mysql_query(\"SELECT * FROM company WHERE companyId='$companyId'\")); "); 
document.writeln(" 		 "); 
document.writeln("            			if(isset($_POST['fertig'])) "); 
document.writeln(" { "); 
document.writeln(" $conn=mysql_connect($host,$user,$pass); "); 
document.writeln(" if(! $conn ) "); 
document.writeln(" { "); 
document.writeln("   die('Could not connect: ' . mysql_error()); "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" $companyId=$company['companyId']; "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" $sql1=\"DELETE FROM company WHERE companyId=$companyId\" ;  "); 
document.writeln(" mysql_select_db($test); "); 
document.writeln("  "); 
document.writeln(" $retval = mysql_query( $sql1, $conn ); "); 
document.writeln("  "); 
document.writeln(" 	 "); 
document.writeln(" 	if(! $retval ) "); 
document.writeln(" { "); 
document.writeln("   die('Could not enter data: ' . mysql_error()); "); 
document.writeln(" } "); 
document.writeln(" echo 'alert(\'Fertig\');'; "); 
document.writeln(" echo 'console.log(\'Fertig\');'; "); 
document.writeln("  "); 
document.writeln(" mysql_close($conn); "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln(" echo '</script>'; "); 
document.writeln(" 	 "); 
document.writeln(" 				 "); 
document.writeln(" 				?> "); 
document.writeln(" 	 "); 
document.writeln(" 	 "); 
document.writeln(" 	               "); 
document.writeln(" 			 "); 
document.writeln(" 			 "); 
document.writeln("             <form method=\"post\" action=\"\" > "); 
document.writeln(" <table width=\"400\" border=\"0\" cellspacing=\"1\" cellpadding=\"2\"> "); 
document.writeln(" <tr> "); 
document.writeln(" <td width=\"100\"></td> "); 
document.writeln(" <td><input value=\"<?=$company['contactPerson_name'];?>\" name=\"subject\" type=\"hidden\" id=\"subject\"></td> "); 
document.writeln(" </tr> "); 
document.writeln(" <tr> "); 
document.writeln("  "); 
document.writeln(" <tr> "); 
document.writeln(" <td width=\"100\"></td> "); 
document.writeln(" <td><input value=\"<?=$company['companyId'];?>\" name=\"companyId\" type=\"hidden\" id=\"companyId\"></td> "); 
document.writeln(" </tr> "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" <!--fertig--> "); 
document.writeln(" <tr> "); 
document.writeln(" <td width=\"100\"></td> "); 
document.writeln(" <td> <input value=\"<?=$company['contactPerson_name'];?>\" name=\"vorname\" type=\"hidden\" id=\"vorname\"></td> "); 
document.writeln(" </tr> "); 
document.writeln("  "); 
document.writeln(" <tr> "); 
document.writeln(" <td width=\"100\"></td> "); 
document.writeln(" <td> <input value=\"<?=$company['adress'];?>\" name=\"strasse\" type=\"hidden\" id=\"strasse\"></td> "); 
document.writeln(" </tr> "); 
document.writeln(" <tr> "); 
document.writeln(" <td width=\"100\"></td> "); 
document.writeln(" <td> <input value=\"<?=$company['password'];?>\" name=\"tel\" type=\"hidden\" id=\"tel\"></td> "); 
document.writeln(" </tr> "); 
document.writeln("  "); 
document.writeln(" </td></tr> "); 
document.writeln("  "); 
document.writeln(" </table> "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" 	 "); 
document.writeln(" 		 "); 
document.writeln("             	<div class=\"company\"> "); 
document.writeln("                   "); 
document.writeln("                 	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"> "); 
document.writeln("                     	<tr> "); 
document.writeln("                             <td align=\"left\" class=\"col1\"> "); 
document.writeln("                     "); 
document.writeln("                           "); 
document.writeln("                                                     "); 
document.writeln("                       "); 
document.writeln(" 								<form action=\"\" method=\"post\">  "); 
document.writeln("                       "); 
document.writeln("                                                "); 
document.writeln("                      "); 
document.writeln("                              "); 
document.writeln("                                  "); 
document.writeln("                     <p class=\"name\" >         <tr><td>Name</td><td> &#160;&#160; <input size=\"30\" type=\"text\" name=\"update_companyName\" id=\"update_companyName\" class=\"txt\" value=\"<?=$company['companyName'];?>\" </td></tr></p> "); 
document.writeln("                                         "); 
document.writeln("       "); 
document.writeln("           "); 
document.writeln("                              <tr><td>&nbsp; </td><td> </td></tr> "); 
document.writeln("          <tr><td>Username</td><td> &#160;&#160;               		 <input size=\"30\" type=\"text\" name=\"update_adress\" id=\"update_adress\" class=\"txt\" value=\"<?=$company['adress'];?>\" />     </td></tr> "); 
document.writeln("                               <tr><td>&nbsp; </td><td> </td></tr> "); 
document.writeln("                                  "); 
document.writeln("                                 <tr><td>E-mail</td><td>&#160;&#160;                                  <input size=\"30\" type=\"text\" name=\"update_website\" id=\"update_website\" class=\"txt\" value=\"<?=$company['website']; ?> \" /> "); 
document.writeln("                   </td></tr> "); 
document.writeln("           <tr><td>&nbsp; </td><td> </td></tr> "); 
document.writeln("                                 "); 
document.writeln("              <tr><td>Password</td><td> &#160;&#160; <input size=\"30\" type=\"text\" name=\"update_password\" id=\"update_password\" class=\"txt\" value=\"<?=$company['password'];?>\" />  "); 
document.writeln(" 		</td></tr> "); 
document.writeln("                   <tr><td>&nbsp; </td><td> </td></tr> "); 
document.writeln("                "); 
document.writeln("                "); 
document.writeln("                                          "); 
document.writeln("              "); 
document.writeln("                  "); 
document.writeln("                 "); 
document.writeln("         <tr><td></td><td> "); 
document.writeln("                 "); 
document.writeln("              "); 
document.writeln(" 		</td></tr> "); 
document.writeln("                 "); 
document.writeln("                 "); 
document.writeln("                <input type=\"hidden\" size=\"1\" type=\"text\" name=\"update_Lat\" id=\"update_Lat\" class=\"txtarea\" value=\"<?=$company['Lat'];?>\"/>   "); 
document.writeln("            <input type=\"hidden\" size=\"1\" type=\"text\" name=\"upda_Lat\" id=\"upda_Lat\" class=\"txtarea\" value=\"<?=$company['Lat'];?>\"/>       "); 
document.writeln("                "); 
document.writeln("                "); 
document.writeln(" 	   "); 
document.writeln("      "); 
document.writeln("       <tr><td></td><td> 	 "); 
document.writeln("       	<p>&nbsp; </p> "); 
document.writeln(" 	 "); 
document.writeln("     <input  type=\"submit\" value=\"Save edit\" name=\"update_send\" onClick=\"alert( 'Save' )\"  style=\"margin-left:-50px; margin-top:20px;\" /> "); 
document.writeln("     <input type=\"submit\" value=\"Delete user\" name=\"fertig\" style=\"margin-left:50px; margin-top:20px;\"  /> "); 
document.writeln(" 		   "); 
document.writeln(" 	     "); 
document.writeln(" </p> "); 
document.writeln("      "); 
document.writeln("      "); 
document.writeln("       <font align=\"right\" size=\"6\" color=\"red\"><?=$company['Lat'];?></font>  "); 
document.writeln(" 	</form> "); 
document.writeln("     </form> "); 
document.writeln("     "); 
document.writeln(" 		 "); 
document.writeln("       "); 
document.writeln("         "); 
document.writeln(" 	</td>								 "); 
document.writeln(" 								 "); 
document.writeln(" 				                         "); 
document.writeln("                     </table> "); 
document.writeln(" <body> "); 
document.writeln(" </html> ");
 // -->
</script>
