<script type="text/javascript">
<!-- 
document.writeln(" <div id=\"overlay\" style=\"position:absolute; top:0; background-color:black; opacity : 0.8; z-index:999;  width:100%; height:100%; display:none;\"></div> "); 
document.writeln("  "); 
document.writeln(" <?php "); 
document.writeln(" 	include(\"miscFunctions.php\"); "); 
document.writeln(" 	if(isset($_POST['signinSend'])) "); 
document.writeln(" 	{ "); 
document.writeln(" 		$username=$_POST['signin_userName']; "); 
document.writeln(" 		$password=md5($_POST['signin_pass']); "); 
document.writeln(" 		 "); 
document.writeln(" 		$control=mysql_fetch_array(mysql_query(\"SELECT COUNT(companyId) AS total FROM company WHERE userId=(SELECT userId FROM user WHERE userName='$username' AND password='$password')\")); "); 
document.writeln(" 		$control=$control['total']; "); 
document.writeln("  "); 
document.writeln(" 		if($control==0) "); 
document.writeln(" 		{ "); 
document.writeln(" 		 echo '<script type=\"text/javascript\">alert(\"Konto nicht gefunden!\");</script>'; "); 
document.writeln(" 		} "); 
document.writeln(" 		else "); 
document.writeln(" 		{ "); 
document.writeln(" 			$data=mysql_fetch_array(mysql_query(\"SELECT companyId,approved FROM company, user WHERE user.userName='$username' AND user.password='$password'\")); "); 
document.writeln(" 			$userId = mysql_fetch_array(mysql_query(\"SELECT userId FROM user WHERE userName='$username' AND password='$password'\")); "); 
document.writeln(" 			$approved = mysql_fetch_array(mysql_query(\"SELECT approved FROM user WHERE userId='$userId'\")); "); 
document.writeln(" 			 "); 
document.writeln(" 			if($data['approved']!='1') "); 
document.writeln(" 			{ "); 
document.writeln(" 				echo '<script type=\"text/javascript\">alert(\"Konto ist nicht aktiviert\");</script>'; "); 
document.writeln(" 			} "); 
document.writeln(" 			else "); 
document.writeln(" 			{	 "); 
document.writeln(" 				$userId2 = $userId['userId']; "); 
document.writeln(" 				$companyId=mysql_fetch_array(mysql_query(\"SELECT companyId FROM company WHERE userId='$userId2'\")); "); 
document.writeln(" 				 "); 
document.writeln(" 				if(isset($_POST['remember'])) "); 
document.writeln(" 					setcookie(\"giris\",$companyId['companyId'],time()+3600*24*3); "); 
document.writeln(" 				else "); 
document.writeln(" 					setcookie(\"giris\",$companyId['companyId'],time()+3600*24); "); 
document.writeln(" 					 "); 
document.writeln(" 				header(\"location:\".$_SERVER['PHP_SELF'].\"?\".$_SERVER['QUERY_STRING']); "); 
document.writeln(" 			} "); 
document.writeln(" 		} "); 
document.writeln(" 	} "); 
document.writeln(" 	 "); 
document.writeln(" 	if(isset($_COOKIE['giris'])) "); 
document.writeln(" 	{ "); 
document.writeln(" 		$id=intval($_COOKIE['giris']); "); 
document.writeln(" 		$control=mysql_fetch_array(mysql_query(\"SELECT COUNT(companyId) AS total FROM company WHERE companyId='$id'\")); "); 
document.writeln(" 		$control=$control['total']; "); 
document.writeln(" 		 "); 
document.writeln(" 		if($control>0) "); 
document.writeln(" 		{ "); 
document.writeln(" 			$data=mysql_fetch_array(mysql_query(\"SELECT companyId FROM company WHERE companyId='$id'\")); "); 
document.writeln(" 			 "); 
document.writeln(" 			$_SESSION['data']=$data; "); 
document.writeln(" 		} "); 
document.writeln(" 	}		 "); 
document.writeln(" ?> "); 
document.writeln(" 	 "); 
document.writeln(" <div id=\"signin\" style=\"display:none;\"> "); 
document.writeln(" 	<p style=\"padding:0;margin:0;color:#246074;font-family:Rockwell;font-size:22px;\">Login</p> "); 
document.writeln(" 	<form action=\"<?=$_SERVER['PHP_SELF'].\"?\".$_SERVER['QUERY_STRING'];?>\" method=\"post\"> "); 
document.writeln(" 	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"> "); 
document.writeln("     	<tr><td style=\"height:10px;\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\">Admin</td><td><input type=\"text\" name=\"signin_userName\" id=\"signin_userName\" class=\"txt\" /></td></tr> "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\">Password</td><td><input type=\"password\" name=\"signin_pass\" id=\"signin_pass\" class=\"txt\" /></td></tr> "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln(" 		<tr><td colspan=\"2\"><input type=\"checkbox\" name=\"remember\" /> Remember my password</td></tr> "); 
document.writeln(" 		<tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("        <tr><td><input type=\"submit\" value=\"Login!\" name=\"signinSend\" /></td></tr> "); 
document.writeln("     </table> "); 
document.writeln(" 	</form> "); 
document.writeln(" </div>	 "); 
document.writeln(" 	 "); 
document.writeln("      "); 
document.writeln("      "); 
document.writeln("      "); 
document.writeln(" <div id=\"signUp\" style=\"display:none;\"> "); 
document.writeln(" 	<p style=\"padding:0;margin:0;color:#246074;font-family:Rockwell;font-size:22px;\">Add User</p> "); 
document.writeln(" 	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"signUptableform\"> "); 
document.writeln("     	<tr><td style=\"height:10px;\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\">Name</td><td><input type=\"text\" name=\"company\" class=\"txt\"  id=\"signUp_company\" /></td></tr>  "); 
document.writeln("          "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\">Username</td><td><input type=\"text\" name=\"contactPerson_name\" id=\"signUp_contactPerson_name\" class=\"txt\"></input></td></tr> "); 
document.writeln("          "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\">Email</td><td><input type=\"text\" name=\"adress\" class=\"txt\" id=\"signUp_adress\" /></td></tr> "); 
document.writeln("     	 "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\">Password</td><td><input type=\"text\" name=\"password\" class=\"txt\" id=\"signUp_password\" /></td></tr> "); 
document.writeln("         "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\"></td><td><input value=\"-\" type=\"hidden\" name=\"email\" class=\"txt\" id=\"signUp_email\" /></td></tr> "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("          "); 
document.writeln("           <tr><td class=\"lbl\"></td><td><input value=\"-\" type=\"hidden\" name=\"userName\" class=\"txt\" id=\"signUp_userName\" /></td></tr> "); 
document.writeln("          "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\"></td><td><input value=\"-\" type=\"hidden\" name=\"name\" class=\"txt\" id=\"signUp_name\" /></td></tr> "); 
document.writeln("          "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         "); 
document.writeln("          "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln(" 		<tr><td class=\"lbl\"></td><td><input value=\"-\" type=\"hidden\" name=\"postalCode\" class=\"txt\" id=\"signUp_postalCode\" /></td></tr> "); 
document.writeln(" 		<tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\"></td><td><input  value=\"-\" type=\"hidden\" class=\"txt\"  id=\"signUp_city\"></tr> "); 
document.writeln("         <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         <tr><td class=\"lbl\"></td><td></td></tr> "); 
document.writeln("        <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("        <tr><td class=\"lbl\"></td><td><input value=\"-\" type=\"hidden\" name=\"title\" id=\"signUp_title\" class=\"txt\" /></td></tr> "); 
document.writeln("            "); 
document.writeln("        <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("         "); 
document.writeln("        <tr><td colspan=\"2\" class=\"Leerzeilen\" style=\"height:15px;\"></td></tr> "); 
document.writeln(" 	   <tr><td colspan=\"2\" align=\"center\">  <a href=\"agb.php\" target=\"_blank\" style=\"color:#246074; text-decoration:none;\"></a>  "); 
document.writeln(" 	   <tr><td colspan=\"2\" class=\"Leerzeilen\"></td></tr> "); 
document.writeln("        <tr><td><input type=\"button\" value=\"Add user!\" id=\"sendTo\" onclick=\"signUp()\" /></td></tr> "); 
document.writeln("     </table> "); 
document.writeln(" 	<p id=\"signUpResult\" style=\"font-family:Myriad Pro; font-size:14px;display:none;\"> "); 
document.writeln(" 		Danke  "); 
document.writeln(" 	</p> "); 
document.writeln(" 	</div> "); 
document.writeln("       "); 
document.writeln(" </div> "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" <div id=\"container\"> "); 
document.writeln(" <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"ustlayout\"> "); 
document.writeln(" <tr><td> "); 
document.writeln("      "); 
document.writeln(" </td><td align=\"right\" valign=\"top\"> "); 
document.writeln("     <div id=\"sagkname\"> "); 
document.writeln("     	<div id=\"benutzer\"> "); 
document.writeln(" 			<?php "); 
document.writeln(" 				if($_SESSION['data'] === null): "); 
document.writeln("                                     //if($_SESSION['data']==null): "); 
document.writeln(" 			?> "); 
document.writeln("         <div align=\"center\">	<a href=\"javascript:openSignInForm()\"><font size=\"20\" >Click to login</font></a> <a href=\"javascript:openSignUpForm()\"></a></div> "); 
document.writeln(" 			<?php "); 
document.writeln(" 				else: "); 
document.writeln(" 			?> "); 
document.writeln(" 				  "); 
document.writeln("               <div align=\"left\">   <a href=\"search.php?was=Designer&wo=&x=71&y=19&type=branche\">Start</a> | <a href=\"javascript:openSignUpForm()\">Add user</a>| "); 
document.writeln(" 				  <a target=\"_blank\" href=\"http://stranica.6te.net/download_excel.php\">Save file</a> | "); 
document.writeln(" 				 <a href=\"logout.php?red=<?=str_replace(\"/\",\"\",$_SERVER['PHP_SELF']).\"?\".$_SERVER['QUERY_STRING'];?>\">Ausloggen</a></div> "); 
document.writeln(" 			<?php "); 
document.writeln(" 				endif; "); 
document.writeln(" 			?> "); 
document.writeln("         </div> "); 
document.writeln("          "); 
document.writeln("     </div> "); 
document.writeln("      "); 
document.writeln(" </td></tr></table> "); 
document.writeln(" </div> "); 
document.writeln(" <div id=\"bar\"> "); 
document.writeln(" 	<div id=\"container\"> "); 
document.writeln("     	<form action=\"search.php\" action=\"get\" onsubmit=\"return formControl()\"> "); 
document.writeln("         <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"arama\"> "); 
document.writeln("             <tr><td>&nbsp;</td><td><div class=\"input\"><input type=\"text\" name=\"was\" id=\"wastxtbx\" onkeyup=\"searchBusiness(this.value)\" "); 
document.writeln("             													value=\"<?=((isset($_GET['was']))?$_GET['was']:'');?>\"  /></div></td> "); 
document.writeln("             	<td style=\"width:200px;\"></td> "); 
document.writeln("                 <td>&nbsp;</td><td><div class=\"input\"><input type=\"text\" name=\"wo\" id=\"wotxtbx\" onkeyup=\"searchPlace(this.value)\" "); 
document.writeln("                 												value=\"<?=((isset($_GET['wo']))?$_GET['wo']:'');?>\" /></div></td> "); 
document.writeln("                  "); 
document.writeln("             </tr> "); 
document.writeln("             <tr> "); 
document.writeln("             	<td></td> "); 
document.writeln("                 	<td style=\"font-size:13px; padding-top:5px;\"> "); 
document.writeln("                     	<div id=\"wasList\" style=\"position:absolute; border:solid 1px #032d3b; background:white; margin-top:-6px;  "); 
document.writeln("                         			width:200px; color:black; display:none; z-index:1000;\"> "); 
document.writeln("                                      "); 
document.writeln("                         </div> "); 
document.writeln("                 	<input type=\"hidden\" name=\"type\" value=\"branche\" id=\"branche\"  "); 
document.writeln(" 							<?=(($_GET['type'] === 'branche')?'checked=\"checked\"':'checked=\"checked\"');?> "); 
document.writeln("                                />   "); 
document.writeln("                     <input type=\"hidden\" name=\"type\" value=\"name\" id=\"name\"  "); 
document.writeln(" 							<?=(($_GET['type']=='name')?'checked=\"checked\"':'');?> />  "); 
document.writeln("                 </td> "); 
document.writeln("                 <td></td> "); 
document.writeln("                 <td></td> "); 
document.writeln("                 <td style=\"font-size:13px; padding-top:5px;\"> "); 
document.writeln("                 	 "); 
document.writeln("                     <div id=\"woList\" style=\"position:absolute; border:solid 1px #032d3b; background:white; margin-top:-23px;  "); 
document.writeln("                         			width:200px; color:black; display:none; z-index:1001;\"> "); 
document.writeln("                                      "); 
document.writeln("                      </div> "); 
document.writeln("                 </td> "); 
document.writeln("             </tr> "); 
document.writeln("         </table> "); 
document.writeln("         </form> "); 
document.writeln("      </div> "); 
document.writeln(" </div> "); 
document.writeln("  ");
 // -->
</script>
